// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRSzOy1LpyOJIV2zHTj0LSB_hU0gTv7Vw',
    appId: '1:9473761437:web:1f4db1c1fc6fa226333474',
    messagingSenderId: '9473761437',
    projectId: 'bitronix-stock',
    authDomain: 'bitronix-stock.firebaseapp.com',
    storageBucket: 'bitronix-stock.firebasestorage.app',
    measurementId: 'G-D6687RQCVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQOFkPOSDnv7wW5-hBS4efljvjHa5dkBA',
    appId: '1:9473761437:android:04421f96179051e6333474',
    messagingSenderId: '9473761437',
    projectId: 'bitronix-stock',
    storageBucket: 'bitronix-stock.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVHV7qYZXzoXqpr3FGJjen5gbg9ALP5Rc',
    appId: '1:9473761437:ios:19cf419f519d5eff333474',
    messagingSenderId: '9473761437',
    projectId: 'bitronix-stock',
    storageBucket: 'bitronix-stock.firebasestorage.app',
    iosBundleId: 'com.example.bitronixStock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRSzOy1LpyOJIV2zHTj0LSB_hU0gTv7Vw',
    appId: '1:9473761437:web:d2a5fdcb2a2f1c22333474',
    messagingSenderId: '9473761437',
    projectId: 'bitronix-stock',
    authDomain: 'bitronix-stock.firebaseapp.com',
    storageBucket: 'bitronix-stock.firebasestorage.app',
    measurementId: 'G-FVTGQP6WSM',
  );
}
